# Generated by Django 5.0.2 on 2024-06-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='apellido',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='nombre',
            new_name='name',
        ),
    ]
