# Generated by Django 5.0.2 on 2024-10-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_personalcaja_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario_perseo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='nombre_usuario_perseo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalcaja',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('JACALA', 'JACALA'), ('ACAXOCHITLAN', 'ACAXOCHITLAN'), ('TENANGO DE DORIA', 'TENANGO DE DORIA'), ('EL CEREZO', 'EL CEREZO'), ('SAN AGUSTIN TLAXIACA', 'SAN AGUSTIN TLAXIACA'), ('SAN JOSE TEPENENE', 'SAN JOSE TEPENENE'), ('ACTOPAN CIMA', 'ACTOPAN CIMA'), ('ACTOPAN OCAMPO', 'ACTOPAN OCAMPO'), ('ACTOPAN TUZO', 'ACTOPAN TUZO'), ('PROGRESO DE OBREGON', 'PROGRESO DE OBREGON'), ('MIXQUIAHUALA', 'MIXQUIAHUALA'), ('TUZO MIXQUIAHUALA', 'TUZO MIXQUIAHUALA'), ('TLAHUELILPAN', 'TLAHUELILPAN'), ('APAXCO TELECABLE', 'APAXCO TELECABLE'), ('TEQUIXQUIAC', 'TEQUIXQUIAC')], max_length=50, null=True),
        ),
    ]
