# Generated by Django 5.0.2 on 2024-12-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agente_personal_nombre_usuario_perseo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcaja',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('JACALA', 'JACALA'), ('ACAXOCHITLAN', 'ACAXOCHITLAN'), ('TENANGO', 'TENANGO'), ('EL CEREZO', 'EL CEREZO'), ('SAN AGUSTIN TLAXIACA', 'SAN AGUSTIN TLAXIACA'), ('SAN JOSE TEPENENE', 'SAN JOSE TEPENENE'), ('ACTOPAN CIMA', 'ACTOPAN CIMA'), ('ACTOPAN OCAMPO', 'ACTOPAN OCAMPO'), ('ACTOPAN TUZO', 'ACTOPAN TUZO'), ('PROGRESO DE OBREGON', 'PROGRESO DE OBREGON'), ('MIXQUIAHUALA', 'MIXQUIAHUALA'), ('TUZO MIXQUIAHUALA', 'TUZO MIXQUIAHUALA'), ('TLAHUELILPAN', 'TLAHUELILPAN'), ('APAXCO TELECABLE', 'APAXCO TELECABLE'), ('TEQUIXQUIAC', 'TEQUIXQUIAC')], max_length=50, null=True),
        ),
    ]
