# Generated by Django 5.0.2 on 2024-08-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_apellido_personal_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ventas', models.PositiveIntegerField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personal')),
            ],
        ),
    ]
