# Generated by Django 5.0.2 on 2024-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('other_field1', models.CharField(max_length=100)),
                ('other_field2', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
